resolver: lts-18.5
packages:
- servant-auth/servant-auth/
- servant-client-core/
- servant-client/
- servant-conduit
- servant-docs/
- servant-foreign/
- servant-http-streams/
- servant-machines/
- servant-pipes/
- servant-server/
- servant-swagger/
- servant/

# allow-newer: true # ignores all bounds, that's a sledgehammer
# - doc/tutorial/

extra-deps:
- hspec-wai-0.10.1
